BEGIN
    CREATE TABLE IF NOT EXISTS IDEA_2_DB.PUBLIC.CUSTOMER (
        CUSTID VARCHAR(50),
        NAME VARCHAR(200),
        EMAILID VARCHAR(200),
        REGION VARCHAR(100)
    );

    CREATE TABLE IF NOT EXISTS IDEA_2_DB.PUBLIC."order" (
        ORDERID VARCHAR(50),
        CUSTID VARCHAR(50),
        ITEMNAME VARCHAR(200),
        PRICEPERUNIT NUMBER(18,2),
        QTY NUMBER(18,0),
        ORDER_DATE DATE,
        STARTDATE DATE,
        ENDDATE DATE,
        ISACTIVE VARCHAR(10)
    );

    RETURN 'Tables CUSTOMER and order created successfully.';
EXCEPTION
    WHEN OTHER THEN
        RETURN OBJECT_CONSTRUCT('error', SQLERRM)::VARCHAR;
END;