BEGIN
    CREATE TABLE IF NOT EXISTS IDEA_2_DB.PUBLIC.PIPELINE_LOG (
        LOG_ID NUMBER AUTOINCREMENT,
        PROCEDURE_NAME VARCHAR(200),
        STATUS VARCHAR(50),
        MESSAGE VARCHAR(4000),
        ROWS_AFFECTED NUMBER,
        CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
    );

    RETURN 'PIPELINE_LOG table created successfully.';
EXCEPTION
    WHEN OTHER THEN
        RETURN OBJECT_CONSTRUCT('error', SQLERRM)::VARCHAR;
END;