CREATE OR REPLACE PROCEDURE IDEA_2_DB.PUBLIC.SP_LOAD_CUSTOMER_DATA()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
BEGIN
    TRUNCATE TABLE IF EXISTS IDEA_2_DB.PUBLIC.CUSTOMER;

    COPY INTO IDEA_2_DB.PUBLIC.CUSTOMER
    FROM @IDEA_2_DB.PUBLIC.SDLC_WIZARD_STAGE/customerdata
    FILE_FORMAT = (
        TYPE = 'CSV'
        SKIP_HEADER = 1
        FIELD_OPTIONALLY_ENCLOSED_BY = '"'
        ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
    )
    ON_ERROR = CONTINUE;

    INSERT INTO IDEA_2_DB.PUBLIC.PIPELINE_LOG (PROCEDURE_NAME, STATUS, MESSAGE, ROWS_AFFECTED)
    SELECT 'SP_LOAD_CUSTOMER_DATA', 'SUCCESS', 'Customer data loaded successfully.', COUNT(*)
    FROM IDEA_2_DB.PUBLIC.CUSTOMER;

    RETURN 'Customer data loaded successfully.';
EXCEPTION
    WHEN OTHER THEN
        INSERT INTO IDEA_2_DB.PUBLIC.PIPELINE_LOG (PROCEDURE_NAME, STATUS, MESSAGE, ROWS_AFFECTED)
        VALUES ('SP_LOAD_CUSTOMER_DATA', 'ERROR', SQLERRM, 0);
        RETURN OBJECT_CONSTRUCT('error', SQLERRM)::VARCHAR;
END;
$$;