CREATE OR REPLACE PROCEDURE IDEA_2_DB.PUBLIC.SP_CLEAN_CUSTOMER_DATA()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    V_DELETED_NULLS NUMBER;
    V_DELETED_DUPES NUMBER;
BEGIN
    -- Remove null records where key fields are null
    DELETE FROM IDEA_2_DB.PUBLIC.CUSTOMER
    WHERE CUSTID IS NULL
       OR NAME IS NULL
       OR EMAILID IS NULL;

    V_DELETED_NULLS := SQLROWCOUNT;

    -- Remove duplicates keeping the first occurrence
    CREATE OR REPLACE TEMPORARY TABLE IDEA_2_DB.PUBLIC.CUSTOMER_CLEAN AS
    SELECT CUSTID, NAME, EMAILID, REGION
    FROM IDEA_2_DB.PUBLIC.CUSTOMER
    QUALIFY ROW_NUMBER() OVER (PARTITION BY CUSTID ORDER BY NAME) = 1;

    LET V_ORIGINAL_COUNT NUMBER := (SELECT COUNT(*) FROM IDEA_2_DB.PUBLIC.CUSTOMER);
    LET V_CLEAN_COUNT NUMBER := (SELECT COUNT(*) FROM IDEA_2_DB.PUBLIC.CUSTOMER_CLEAN);

    V_DELETED_DUPES := :V_ORIGINAL_COUNT - :V_CLEAN_COUNT;

    TRUNCATE TABLE IDEA_2_DB.PUBLIC.CUSTOMER;

    INSERT INTO IDEA_2_DB.PUBLIC.CUSTOMER
    SELECT CUSTID, NAME, EMAILID, REGION
    FROM IDEA_2_DB.PUBLIC.CUSTOMER_CLEAN;

    DROP TABLE IF EXISTS IDEA_2_DB.PUBLIC.CUSTOMER_CLEAN;

    INSERT INTO IDEA_2_DB.PUBLIC.PIPELINE_LOG (PROCEDURE_NAME, STATUS, MESSAGE, ROWS_AFFECTED)
    VALUES ('SP_CLEAN_CUSTOMER_DATA', 'SUCCESS',
            'Nulls removed: ' || :V_DELETED_NULLS || ', Duplicates removed: ' || :V_DELETED_DUPES,
            :V_DELETED_NULLS + :V_DELETED_DUPES);

    RETURN 'Customer data cleaned. Nulls removed: ' || :V_DELETED_NULLS || ', Duplicates removed: ' || :V_DELETED_DUPES;
EXCEPTION
    WHEN OTHER THEN
        INSERT INTO IDEA_2_DB.PUBLIC.PIPELINE_LOG (PROCEDURE_NAME, STATUS, MESSAGE, ROWS_AFFECTED)
        VALUES ('SP_CLEAN_CUSTOMER_DATA', 'ERROR', SQLERRM, 0);
        RETURN OBJECT_CONSTRUCT('error', SQLERRM)::VARCHAR;
END;
$$;