CREATE OR REPLACE PROCEDURE IDEA_2_DB.PUBLIC.SP_CLEAN_ORDER_DATA()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    V_DELETED_NULLS NUMBER;
    V_DELETED_DUPES NUMBER;
BEGIN
    -- Remove null records where key fields are null
    DELETE FROM IDEA_2_DB.PUBLIC."order"
    WHERE ORDERID IS NULL
       OR CUSTID IS NULL
       OR ITEMNAME IS NULL;

    V_DELETED_NULLS := SQLROWCOUNT;

    -- Remove duplicates keeping the first occurrence
    CREATE OR REPLACE TEMPORARY TABLE IDEA_2_DB.PUBLIC.ORDER_CLEAN AS
    SELECT ORDERID, CUSTID, ITEMNAME, PRICEPERUNIT, QTY, ORDER_DATE, STARTDATE, ENDDATE, ISACTIVE
    FROM IDEA_2_DB.PUBLIC."order"
    QUALIFY ROW_NUMBER() OVER (PARTITION BY ORDERID ORDER BY ORDER_DATE DESC) = 1;

    LET V_ORIGINAL_COUNT NUMBER := (SELECT COUNT(*) FROM IDEA_2_DB.PUBLIC."order");
    LET V_CLEAN_COUNT NUMBER := (SELECT COUNT(*) FROM IDEA_2_DB.PUBLIC.ORDER_CLEAN);

    V_DELETED_DUPES := :V_ORIGINAL_COUNT - :V_CLEAN_COUNT;

    TRUNCATE TABLE IDEA_2_DB.PUBLIC."order";

    INSERT INTO IDEA_2_DB.PUBLIC."order"
    SELECT ORDERID, CUSTID, ITEMNAME, PRICEPERUNIT, QTY, ORDER_DATE, STARTDATE, ENDDATE, ISACTIVE
    FROM IDEA_2_DB.PUBLIC.ORDER_CLEAN;

    DROP TABLE IF EXISTS IDEA_2_DB.PUBLIC.ORDER_CLEAN;

    INSERT INTO IDEA_2_DB.PUBLIC.PIPELINE_LOG (PROCEDURE_NAME, STATUS, MESSAGE, ROWS_AFFECTED)
    VALUES ('SP_CLEAN_ORDER_DATA', 'SUCCESS',
            'Nulls removed: ' || :V_DELETED_NULLS || ', Duplicates removed: ' || :V_DELETED_DUPES,
            :V_DELETED_NULLS + :V_DELETED_DUPES);

    RETURN 'Order data cleaned. Nulls removed: ' || :V_DELETED_NULLS || ', Duplicates removed: ' || :V_DELETED_DUPES;
EXCEPTION
    WHEN OTHER THEN
        INSERT INTO IDEA_2_DB.PUBLIC.PIPELINE_LOG (PROCEDURE_NAME, STATUS, MESSAGE, ROWS_AFFECTED)
        VALUES ('SP_CLEAN_ORDER_DATA', 'ERROR', SQLERRM, 0);
        RETURN OBJECT_CONSTRUCT('error', SQLERRM)::VARCHAR;
END;
$$;