BEGIN
    CREATE TABLE IF NOT EXISTS IDEA_2_DB.PUBLIC.ORDERSUMMARY (
        ORDERID VARCHAR(50),
        CUSTID VARCHAR(50),
        NAME VARCHAR(200),
        EMAILID VARCHAR(200),
        REGION VARCHAR(100),
        ITEMNAME VARCHAR(200),
        PRICEPERUNIT NUMBER(18,2),
        QTY NUMBER(18,0),
        TOTALAMOUNT NUMBER(18,2),
        ORDER_DATE DATE,
        STARTDATE DATE,
        ENDDATE DATE,
        ISACTIVE VARCHAR(10),
        IS_CURRENT BOOLEAN DEFAULT TRUE,
        EFFECTIVE_FROM TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
        EFFECTIVE_TO TIMESTAMP_NTZ DEFAULT '9999-12-31'::TIMESTAMP_NTZ
    );

    RETURN 'ORDERSUMMARY table created successfully.';
EXCEPTION
    WHEN OTHER THEN
        RETURN OBJECT_CONSTRUCT('error', SQLERRM)::VARCHAR;
END;