CREATE OR REPLACE PROCEDURE IDEA_2_DB.PUBLIC.SP_LOAD_ORDERSUMMARY()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    V_ROWS_INSERTED NUMBER;
BEGIN
    -- Validate source data exists
    LET V_CUST_COUNT NUMBER := (SELECT COUNT(*) FROM IDEA_2_DB.PUBLIC.CUSTOMER);
    LET V_ORD_COUNT NUMBER := (SELECT COUNT(*) FROM IDEA_2_DB.PUBLIC."order");

    IF (:V_CUST_COUNT = 0) THEN
        INSERT INTO IDEA_2_DB.PUBLIC.PIPELINE_LOG (PROCEDURE_NAME, STATUS, MESSAGE, ROWS_AFFECTED)
        VALUES ('SP_LOAD_ORDERSUMMARY', 'WARNING', 'Customer table is empty. No data to load.', 0);
        RETURN 'Warning: Customer table is empty. No data loaded into ORDERSUMMARY.';
    END IF;

    IF (:V_ORD_COUNT = 0) THEN
        INSERT INTO IDEA_2_DB.PUBLIC.PIPELINE_LOG (PROCEDURE_NAME, STATUS, MESSAGE, ROWS_AFFECTED)
        VALUES ('SP_LOAD_ORDERSUMMARY', 'WARNING', 'Order table is empty. No data to load.', 0);
        RETURN 'Warning: Order table is empty. No data loaded into ORDERSUMMARY.';
    END IF;

    -- Merge data into ordersummary
    MERGE INTO IDEA_2_DB.PUBLIC.ORDERSUMMARY TGT
    USING (
        SELECT
            O.ORDERID,
            O.CUSTID,
            C.NAME,
            C.EMAILID,
            C.REGION,
            O.ITEMNAME,
            O.PRICEPERUNIT,
            O.QTY,
            O.PRICEPERUNIT * O.QTY AS TOTALAMOUNT,
            O.ORDER_DATE,
            O.STARTDATE,
            O.ENDDATE,
            O.ISACTIVE
        FROM IDEA_2_DB.PUBLIC."order" O
        INNER JOIN IDEA_2_DB.PUBLIC.CUSTOMER C
            ON O.CUSTID = C.CUSTID
    ) SRC
    ON TGT.ORDERID = SRC.ORDERID AND TGT.IS_CURRENT = TRUE
    WHEN MATCHED AND (
        TGT.NAME <> SRC.NAME OR
        TGT.EMAILID <> SRC.EMAILID OR
        TGT.REGION <> SRC.REGION OR
        TGT.ITEMNAME <> SRC.ITEMNAME OR
        TGT.PRICEPERUNIT <> SRC.PRICEPERUNIT OR
        TGT.QTY <> SRC.QTY OR
        TGT.TOTALAMOUNT <> SRC.TOTALAMOUNT
    ) THEN UPDATE
        SET TGT.IS_CURRENT = FALSE,
            TGT.EFFECTIVE_TO = CURRENT_TIMESTAMP(),
            TGT.ISACTIVE = 'N',
            TGT.ENDDATE = CURRENT_DATE()
    WHEN NOT MATCHED THEN INSERT (
        ORDERID, CUSTID, NAME, EMAILID, REGION, ITEMNAME,
        PRICEPERUNIT, QTY, TOTALAMOUNT, ORDER_DATE, STARTDATE, ENDDATE,
        ISACTIVE, IS_CURRENT, EFFECTIVE_FROM, EFFECTIVE_TO
    ) VALUES (
        SRC.ORDERID, SRC.CUSTID, SRC.NAME, SRC.EMAILID, SRC.REGION, SRC.ITEMNAME,
        SRC.PRICEPERUNIT, SRC.QTY, SRC.TOTALAMOUNT, SRC.ORDER_DATE, SRC.STARTDATE, SRC.ENDDATE,
        SRC.ISACTIVE, TRUE, CURRENT_TIMESTAMP(), '9999-12-31'::TIMESTAMP_NTZ
    );

    -- Insert new versions of updated records
    INSERT INTO IDEA_2_DB.PUBLIC.ORDERSUMMARY (
        ORDERID, CUSTID, NAME, EMAILID, REGION, ITEMNAME,
        PRICEPERUNIT, QTY, TOTALAMOUNT, ORDER_DATE, STARTDATE, ENDDATE,
        ISACTIVE, IS_CURRENT, EFFECTIVE_FROM, EFFECTIVE_TO
    )
    SELECT
        O.ORDERID,
        O.CUSTID,
        C.NAME,
        C.EMAILID,
        C.REGION,
        O.ITEMNAME,
        O.PRICEPERUNIT,
        O.QTY,
        O.PRICEPERUNIT * O.QTY AS TOTALAMOUNT,
        O.ORDER_DATE,
        O.STARTDATE,
        O.ENDDATE,
        O.ISACTIVE,
        TRUE,
        CURRENT_TIMESTAMP(),
        '9999-12-31'::TIMESTAMP_NTZ
    FROM IDEA_2_DB.PUBLIC."order" O
    INNER JOIN IDEA_2_DB.PUBLIC.CUSTOMER C
        ON O.CUSTID = C.CUSTID
    INNER JOIN IDEA_2_DB.PUBLIC.ORDERSUMMARY OS
        ON O.ORDERID = OS.ORDERID
        AND OS.IS_CURRENT = FALSE
        AND OS.EFFECTIVE_TO >= DATEADD('SECOND', -5, CURRENT_TIMESTAMP())
    WHERE NOT EXISTS (
        SELECT 1 FROM IDEA_2_DB.PUBLIC.ORDERSUMMARY X
        WHERE X.ORDERID = O.ORDERID AND X.IS_CURRENT = TRUE
    );

    V_ROWS_INSERTED := SQLROWCOUNT;

    INSERT INTO IDEA_2_DB.PUBLIC.PIPELINE_LOG (PROCEDURE_NAME, STATUS, MESSAGE, ROWS_AFFECTED)
    VALUES ('SP_LOAD_ORDERSUMMARY', 'SUCCESS', 'Order summary loaded/updated successfully.', :V_ROWS_INSERTED);

    RETURN 'Order summary loaded successfully. Rows affected: ' || :V_ROWS_INSERTED;
EXCEPTION
    WHEN OTHER THEN
        INSERT INTO IDEA_2_DB.PUBLIC.PIPELINE_LOG (PROCEDURE_NAME, STATUS, MESSAGE, ROWS_AFFECTED)
        VALUES ('SP_LOAD_ORDERSUMMARY', 'ERROR', SQLERRM, 0);
        RETURN OBJECT_CONSTRUCT('error', SQLERRM)::VARCHAR;
END;
$$;