BEGIN
    CREATE TABLE IF NOT EXISTS IDEA_2_DB.PUBLIC.CUSTOMER_SCD2 (
        CUSTID VARCHAR(50),
        NAME VARCHAR(200),
        EMAILID VARCHAR(200),
        REGION VARCHAR(100),
        IS_CURRENT BOOLEAN DEFAULT TRUE,
        EFFECTIVE_FROM TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
        EFFECTIVE_TO TIMESTAMP_NTZ DEFAULT '9999-12-31'::TIMESTAMP_NTZ
    );

    RETURN 'CUSTOMER_SCD2 table created successfully.';
EXCEPTION
    WHEN OTHER THEN
        RETURN OBJECT_CONSTRUCT('error', SQLERRM)::VARCHAR;
END;