CREATE OR REPLACE PROCEDURE IDEA_2_DB.PUBLIC.SP_UPDATE_CUSTOMER_SCD2()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    V_UPDATED NUMBER;
    V_INSERTED NUMBER;
BEGIN
    -- Expire existing records that have changed
    UPDATE IDEA_2_DB.PUBLIC.CUSTOMER_SCD2 TGT
    SET IS_CURRENT = FALSE,
        EFFECTIVE_TO = CURRENT_TIMESTAMP()
    WHERE TGT.IS_CURRENT = TRUE
      AND EXISTS (
          SELECT 1 FROM IDEA_2_DB.PUBLIC.CUSTOMER SRC
          WHERE SRC.CUSTID = TGT.CUSTID
            AND (SRC.NAME <> TGT.NAME OR SRC.EMAILID <> TGT.EMAILID OR SRC.REGION <> TGT.REGION)
      );

    V_UPDATED := SQLROWCOUNT;

    -- Insert new current records for changed customers
    INSERT INTO IDEA_2_DB.PUBLIC.CUSTOMER_SCD2 (CUSTID, NAME, EMAILID, REGION, IS_CURRENT, EFFECTIVE_FROM, EFFECTIVE_TO)
    SELECT
        SRC.CUSTID,
        SRC.NAME,
        SRC.EMAILID,
        SRC.REGION,
        TRUE,
        CURRENT_TIMESTAMP(),
        '9999-12-31'::TIMESTAMP_NTZ
    FROM IDEA_2_DB.PUBLIC.CUSTOMER SRC
    WHERE NOT EXISTS (
        SELECT 1 FROM IDEA_2_DB.PUBLIC.CUSTOMER_SCD2 TGT
        WHERE TGT.CUSTID = SRC.CUSTID
          AND TGT.IS_CURRENT = TRUE
    );

    V_INSERTED := SQLROWCOUNT;

    INSERT INTO IDEA_2_DB.PUBLIC.PIPELINE_LOG (PROCEDURE_NAME, STATUS, MESSAGE, ROWS_AFFECTED)
    VALUES ('SP_UPDATE_CUSTOMER_SCD2', 'SUCCESS',
            'Records expired: ' || :V_UPDATED || ', Records inserted: ' || :V_INSERTED,
            :V_UPDATED + :V_INSERTED);

    RETURN 'Customer SCD2 updated. Expired: ' || :V_UPDATED || ', Inserted: ' || :V_INSERTED;
EXCEPTION
    WHEN OTHER THEN
        INSERT INTO IDEA_2_DB.PUBLIC.PIPELINE_LOG (PROCEDURE_NAME, STATUS, MESSAGE, ROWS_AFFECTED)
        VALUES ('SP_UPDATE_CUSTOMER_SCD2', 'ERROR', SQLERRM, 0);
        RETURN OBJECT_CONSTRUCT('error', SQLERRM)::VARCHAR;
END;
$$;