CREATE OR REPLACE PROCEDURE IDEA_2_DB.PUBLIC.SP_UPDATE_ORDERSUMMARY_ON_CUSTOMER_CHANGE()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    V_EXPIRED NUMBER;
    V_INSERTED NUMBER;
BEGIN
    -- Identify ordersummary records where customer data has changed
    -- Mark old records as inactive
    UPDATE IDEA_2_DB.PUBLIC.ORDERSUMMARY OS
    SET IS_CURRENT = FALSE,
        EFFECTIVE_TO = CURRENT_TIMESTAMP(),
        ISACTIVE = 'N',
        ENDDATE = CURRENT_DATE()
    WHERE OS.IS_CURRENT = TRUE
      AND EXISTS (
          SELECT 1 FROM IDEA_2_DB.PUBLIC.CUSTOMER C
          WHERE C.CUSTID = OS.CUSTID
            AND (C.NAME <> OS.NAME OR C.EMAILID <> OS.EMAILID OR C.REGION <> OS.REGION)
      );

    V_EXPIRED := SQLROWCOUNT;

    -- Insert new active records with updated customer info
    INSERT INTO IDEA_2_DB.PUBLIC.ORDERSUMMARY (
        ORDERID, CUSTID, NAME, EMAILID, REGION, ITEMNAME,
        PRICEPERUNIT, QTY, TOTALAMOUNT, ORDER_DATE, STARTDATE, ENDDATE,
        ISACTIVE, IS_CURRENT, EFFECTIVE_FROM, EFFECTIVE_TO
    )
    SELECT
        OS.ORDERID,
        OS.CUSTID,
        C.NAME,
        C.EMAILID,
        C.REGION,
        OS.ITEMNAME,
        OS.PRICEPERUNIT,
        OS.QTY,
        OS.TOTALAMOUNT,
        OS.ORDER_DATE,
        CURRENT_DATE(),
        NULL,
        'Y',
        TRUE,
        CURRENT_TIMESTAMP(),
        '9999-12-31'::TIMESTAMP_NTZ
    FROM IDEA_2_DB.PUBLIC.ORDERSUMMARY OS
    INNER JOIN IDEA_2_DB.PUBLIC.CUSTOMER C
        ON C.CUSTID = OS.CUSTID
    WHERE OS.IS_CURRENT = FALSE
      AND OS.EFFECTIVE_TO >= DATEADD('SECOND', -5, CURRENT_TIMESTAMP())
      AND NOT EXISTS (
          SELECT 1 FROM IDEA_2_DB.PUBLIC.ORDERSUMMARY X
          WHERE X.ORDERID = OS.ORDERID AND X.IS_CURRENT = TRUE
      );

    V_INSERTED := SQLROWCOUNT;

    INSERT INTO IDEA_2_DB.PUBLIC.PIPELINE_LOG (PROCEDURE_NAME, STATUS, MESSAGE, ROWS_AFFECTED)
    VALUES ('SP_UPDATE_ORDERSUMMARY_ON_CUSTOMER_CHANGE', 'SUCCESS',
            'Records expired: ' || :V_EXPIRED || ', New records inserted: ' || :V_INSERTED,
            :V_EXPIRED + :V_INSERTED);

    RETURN 'Ordersummary SCD2 updated. Expired: ' || :V_EXPIRED || ', Inserted: ' || :V_INSERTED;
EXCEPTION
    WHEN OTHER THEN
        INSERT INTO IDEA_2_DB.PUBLIC.PIPELINE_LOG (PROCEDURE_NAME, STATUS, MESSAGE, ROWS_AFFECTED)
        VALUES ('SP_UPDATE_ORDERSUMMARY_ON_CUSTOMER_CHANGE', 'ERROR', SQLERRM, 0);
        RETURN OBJECT_CONSTRUCT('error', SQLERRM)::VARCHAR;
END;
$$;