BEGIN
    CREATE TABLE IF NOT EXISTS IDEA_2_DB.PUBLIC.CUSTOMERAGGREGATESPEND (
        NAME VARCHAR(200),
        ORDER_DATE DATE,
        TOTAL_SPEND NUMBER(18,2),
        RECORD_COUNT NUMBER,
        CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
    );

    RETURN 'CUSTOMERAGGREGATESPEND table created successfully.';
EXCEPTION
    WHEN OTHER THEN
        RETURN OBJECT_CONSTRUCT('error', SQLERRM)::VARCHAR;
END;