CREATE OR REPLACE PROCEDURE IDEA_2_DB.PUBLIC.SP_LOAD_CUSTOMERAGGREGATESPEND()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    V_ROWS_INSERTED NUMBER;
BEGIN
    -- Validate source data exists
    LET V_OS_COUNT NUMBER := (SELECT COUNT(*) FROM IDEA_2_DB.PUBLIC.ORDERSUMMARY WHERE IS_CURRENT = TRUE);

    IF (:V_OS_COUNT = 0) THEN
        INSERT INTO IDEA_2_DB.PUBLIC.PIPELINE_LOG (PROCEDURE_NAME, STATUS, MESSAGE, ROWS_AFFECTED)
        VALUES ('SP_LOAD_CUSTOMERAGGREGATESPEND', 'WARNING', 'Ordersummary table has no current records.', 0);
        RETURN 'Warning: No current records in ORDERSUMMARY. No data loaded.';
    END IF;

    -- Truncate and reload aggregate table
    TRUNCATE TABLE IF EXISTS IDEA_2_DB.PUBLIC.CUSTOMERAGGREGATESPEND;

    INSERT INTO IDEA_2_DB.PUBLIC.CUSTOMERAGGREGATESPEND (NAME, ORDER_DATE, TOTAL_SPEND, RECORD_COUNT, CREATED_AT)
    SELECT
        NAME,
        ORDER_DATE,
        SUM(TOTALAMOUNT) AS TOTAL_SPEND,
        COUNT(*) AS RECORD_COUNT,
        CURRENT_TIMESTAMP()
    FROM IDEA_2_DB.PUBLIC.ORDERSUMMARY
    WHERE IS_CURRENT = TRUE
    GROUP BY NAME, ORDER_DATE
    ORDER BY NAME, ORDER_DATE;

    V_ROWS_INSERTED := SQLROWCOUNT;

    INSERT INTO IDEA_2_DB.PUBLIC.PIPELINE_LOG (PROCEDURE_NAME, STATUS, MESSAGE, ROWS_AFFECTED)
    VALUES ('SP_LOAD_CUSTOMERAGGREGATESPEND', 'SUCCESS',
            'Customer aggregate spend loaded successfully.',
            :V_ROWS_INSERTED);

    RETURN 'Customer aggregate spend loaded. Rows inserted: ' || :V_ROWS_INSERTED;
EXCEPTION
    WHEN OTHER THEN
        INSERT INTO IDEA_2_DB.PUBLIC.PIPELINE_LOG (PROCEDURE_NAME, STATUS, MESSAGE, ROWS_AFFECTED)
        VALUES ('SP_LOAD_CUSTOMERAGGREGATESPEND', 'ERROR', SQLERRM, 0);
        RETURN OBJECT_CONSTRUCT('error', SQLERRM)::VARCHAR;
END;
$$;