CREATE OR REPLACE PROCEDURE IDEA_2_DB.PUBLIC.SP_MASTER_PIPELINE()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    V_RESULT VARCHAR;
    V_STEP VARCHAR;
BEGIN
    -- Step 1: Load Customer Data
    V_STEP := 'LOAD_CUSTOMER_DATA';
    CALL IDEA_2_DB.PUBLIC.SP_LOAD_CUSTOMER_DATA();

    -- Step 2: Load Order Data
    V_STEP := 'LOAD_ORDER_DATA';
    CALL IDEA_2_DB.PUBLIC.SP_LOAD_ORDER_DATA();

    -- Step 3: Clean Customer Data
    V_STEP := 'CLEAN_CUSTOMER_DATA';
    CALL IDEA_2_DB.PUBLIC.SP_CLEAN_CUSTOMER_DATA();

    -- Step 4: Clean Order Data
    V_STEP := 'CLEAN_ORDER_DATA';
    CALL IDEA_2_DB.PUBLIC.SP_CLEAN_ORDER_DATA();

    -- Step 5: Update Customer SCD2
    V_STEP := 'UPDATE_CUSTOMER_SCD2';
    CALL IDEA_2_DB.PUBLIC.SP_UPDATE_CUSTOMER_SCD2();

    -- Step 6: Load Order Summary
    V_STEP := 'LOAD_ORDERSUMMARY';
    CALL IDEA_2_DB.PUBLIC.SP_LOAD_ORDERSUMMARY();

    -- Step 7: Update Order Summary on Customer Changes
    V_STEP := 'UPDATE_ORDERSUMMARY_SCD2';
    CALL IDEA_2_DB.PUBLIC.SP_UPDATE_ORDERSUMMARY_ON_CUSTOMER_CHANGE();

    -- Step 8: Load Customer Aggregate Spend
    V_STEP := 'LOAD_CUSTOMERAGGREGATESPEND';
    CALL IDEA_2_DB.PUBLIC.SP_LOAD_CUSTOMERAGGREGATESPEND();

    INSERT INTO IDEA_2_DB.PUBLIC.PIPELINE_LOG (PROCEDURE_NAME, STATUS, MESSAGE, ROWS_AFFECTED)
    VALUES ('SP_MASTER_PIPELINE', 'SUCCESS', 'Full pipeline executed successfully.', 0);

    RETURN 'Pipeline executed successfully. All steps completed.';
EXCEPTION
    WHEN OTHER THEN
        INSERT INTO IDEA_2_DB.PUBLIC.PIPELINE_LOG (PROCEDURE_NAME, STATUS, MESSAGE, ROWS_AFFECTED)
        VALUES ('SP_MASTER_PIPELINE', 'ERROR', 'Failed at step: ' || :V_STEP || ' - ' || SQLERRM, 0);
        RETURN OBJECT_CONSTRUCT('error', 'Failed at step: ' || :V_STEP || ' - ' || SQLERRM)::VARCHAR;
END;
$$;